apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userlog-data
  namespace: eda-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # app-set: ${logStorageSize}
