//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogFileInfo) DeepCopyInto(out *LogFileInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogFileInfo.
func (in *LogFileInfo) DeepCopy() *LogFileInfo {
	if in == nil {
		return nil
	}
	out := new(LogFileInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubsystemHealth) DeepCopyInto(out *SubsystemHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubsystemHealth.
func (in *SubsystemHealth) DeepCopy() *SubsystemHealth {
	if in == nil {
		return nil
	}
	out := new(SubsystemHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserLogConfig) DeepCopyInto(out *UserLogConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserLogConfig.
func (in *UserLogConfig) DeepCopy() *UserLogConfig {
	if in == nil {
		return nil
	}
	out := new(UserLogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserLogConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserLogConfigList) DeepCopyInto(out *UserLogConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UserLogConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserLogConfigList.
func (in *UserLogConfigList) DeepCopy() *UserLogConfigList {
	if in == nil {
		return nil
	}
	out := new(UserLogConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserLogConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserLogConfigSpec) DeepCopyInto(out *UserLogConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserLogConfigSpec.
func (in *UserLogConfigSpec) DeepCopy() *UserLogConfigSpec {
	if in == nil {
		return nil
	}
	out := new(UserLogConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserLogConfigStatus) DeepCopyInto(out *UserLogConfigStatus) {
	*out = *in
	if in.LogFiles != nil {
		in, out := &in.LogFiles, &out.LogFiles
		*out = make([]LogFileInfo, len(*in))
		copy(*out, *in)
	}
	out.Subsystems = in.Subsystems
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserLogConfigStatus.
func (in *UserLogConfigStatus) DeepCopy() *UserLogConfigStatus {
	if in == nil {
		return nil
	}
	out := new(UserLogConfigStatus)
	in.DeepCopyInto(out)
	return out
}
